import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { sarabun } from "../../fonts";
import { Toaster } from "@/components/ui/sonner"

// font
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Auth E-COMMERCE",
    description: "Generated by create next app",
};

export default function RootAuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <html lang="en">
        <body
            className={sarabun.className}
            // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            {children}
            <Toaster richColors={true} />
        </body>
    </html>
    );
}
